### ISSUE TITLE
Gameplay Prototype Checklist

### ISSUE THREAD

**Issue by behindcurtain3** [Pulsar4xDevs/Pulsar4x#393]
- [ ] Combat (Elle asteroid, should destroy Earth colony if player fails to destroy it)
- [x] Sensors
- [x] Jump points (Should be able to survey and jump through them)
- [ ] Industry balance pass
- [x] Survey system bodies
- [x] Colonize system bodies
- [x] Fleet Navigation / Orders (semi-working currently)
- [x] Event Log
